name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - run: dir -Recurse > dir.txt

#    - name: Test
#      working-directory: ${{github.workspace}}/build
#      # Execute tests defined by the CMake configuration.
#      run: ctest -C ${{env.BUILD_TYPE}}

# https://github.com/marketplace/actions/upload-files-to-a-github-release
# https://github.com/svenstaro/upload-release-action
#    - name: Upload binaries to release
#      uses: svenstaro/upload-release-action@v2
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: target/release/mything
#        asset_name: mything
#        tag: ${{ github.ref }}
#        overwrite: true
#        body: "This is my release text"

    - run: echo ${{ github.sha }} > Release.txt
    
# https://github.com/marketplace/actions/easy-zip-files
    - uses: vimtor/action-zip@v1.2
      with:
        files: dist/ Release.txt
        recursive: false
        dest: result.zip
# Troubleshoot
    - uses: actions/upload-artifact@v1.1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/result.zip
    
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/release/hello.exe
